apiVersion: v2
name: pizza-shop
description: Pizza shop distributed tracing demo across Spring Boot Kafka microservices
type: application
version: 0.1.0
appVersion: "0.0.1"

dependencies:
  - name: kafka
    version: "32.x.x"
    repository: https://charts.bitnami.com/bitnami
  - name: loki-stack
    version: "2.x.x"
    repository: https://grafana.github.io/helm-charts
