image:
  registry: ghcr.io
  repository: dermotmburke
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

extraEnvFrom: []

kafka:
  bootstrapServers: kafka:9092
  securityProtocol: PLAINTEXT
  truststoreLocation: ""
  truststorePassword: ""
  truststoreType: JKS
  saslMechanism: ""
  saslJaasConfig: ""

datadog:
  agentZipkinPort: 9411

webReceiver:
  replicaCount: 1
  port: 10010
  service:
    type: ClusterIP
    nodePort: null
  ingress:
    enabled: false
    className: ""
    host: pizza-shop.local
    annotations: {}

transformer:
  replicaCount: 1
  port: 10011

repository:
  replicaCount: 1
  port: 10012
